### ISSUE TITLE
采用golang来做后台服务，是否更好？

### ISSUE THREAD

**Issue by Leadrive** [harry-xqb/rent-house#2]
我之前也从事过一段时间的JAVA，感觉过于庞大。
目前在用golang，采用微服务的方式，用得很爽。
我现在是基于faygo来提供服务，供参考。

**Comment by harry-xqb** [comment]
我没有深入了解go不太好回复您的问题。 但是就后台服务来说，Java的生态和社区是很完善的。就做项目来说，还是选择自己熟悉的技术栈来完成比较合适。不过go近来在微服务方面很热门，又出生名门，是值得学习的。
